
server:
  port: 8080
spring:
  application:
    name: proxy
  profiles:
    active: ${SPRING_PROFILES_ACTIVE}
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICE_URL_DEFAULT_ZONE}