server:
  port: 4004
spring:
  application:
    name: product-instance-management
  datasource:
    url: jdbc:postgresql://localhost:5432/smartiq_om
    username: postgres
    password: secret
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: public
        show_sql: false
        format_sql: false
        generate_statistics: false
eureka:
  client:
    service-url:
      defaultZone: http://localhost:4002/eureka