server:
  port: 4002
spring:
  application:
    name: discovery-service
eureka:
  client:
    service-url:
      defaultZone: http://localhost:4002/eureka
  server:
    wait-time-in-ms-when-sync-empty: 0
  instance:
    hostname: localhost
    lease-renewal-interval-in-seconds: 3
    prefer-ip-address: true